version: "{build}"
clone_folder: c:\gopath\src\github.com\mastahyeti\certstore
environment:
  GOPATH: c:\gopath

install:
  - set PATH=%PATH%;C:\msys64\mingw64\bin
  - go version
  - go get -t -v ./...
build_script:
  - go build
test_script:
  - go test -v
