version: "{build}"
clone_folder: c:\gopath\src\github.com\mastahyeti\certstore
environment:
  GOPATH: c:\gopath
  GCC_PATH: mingw_64

install:
  - go version
  - go get -t -v ./...
build_script:
  - go build
test_script:
  - go test -v
