#!/bin/bash
cd "$(dirname "$0")/../test_data"

set -e

# Wipe out old data
rm -rf ca.db.*
rm -f certstore*

# Regenerate our CA
mkdir ca.db.certs
touch ca.db.index
openssl req -new -x509 -days 3650 -nodes -newkey rsa:2048 -sha256 -subj "/O=certstore/OU=ca/CN=ca" -keyout certstore-ca.key -out certstore-ca.crt -config openssl.cnf
openssl pkcs12 -export -out certstore-ca.pfx -inkey certstore-ca.key -in certstore-ca.crt -passout pass:asdf

# regenerate RSA cert/key/pfx
openssl req -newkey rsa:2048 -nodes -sha256 -subj "/O=certstore/OU=leaf/CN=rsa" -keyout certstore-rsa.key -config openssl.cnf -out certstore-rsa.req
openssl ca -batch -days 3650 -create_serial -config openssl.cnf -out certstore-rsa.crt -infiles certstore-rsa.req
openssl pkcs12 -export -out certstore-rsa.pfx -inkey certstore-rsa.key -in certstore-rsa.crt -passout pass:asdf

# regenerate EC cert/key/pfx
openssl req -newkey ec:<(openssl ecparam -name prime256v1) -nodes -sha256 -subj "/O=certstore/OU=leaf/CN=ec" -keyout certstore-ec.key -config openssl.cnf -out certstore-ec.req
openssl ca -batch -days 3650 -create_serial -config openssl.cnf -out certstore-ec.crt -infiles certstore-ec.req
openssl pkcs12 -export -out certstore-ec.pfx -inkey certstore-ec.key -in certstore-ec.crt -passout pass:asdf
